export const address = {
	Division: {
		District: ["Thana"],
	},
	Barisal: {
		District: ["Thana"],
		Barisal: [
			"Agailjhara",
			"Babuganj",
			"Bakerganj",
			"Banaripara",
			"Barisal Sadar",
			"Gournadi",
			"Hizla",
			"Mehendiganj",
			"Muladi",
			"Wazirpur",
		],
		Barguna: [
			"Amtali",
			"Bamna",
			"Barguna Sadar",
			"Betagi",
			"Patharghata",
			"Taltali",
		],
		Bhola: [
			"Bhola Sadar",
			"Daulatkhan",
			"Burhanuddin",
			"Tazumuddin",
			"Lalmohan",
			"Char Fasson",
			"Manpura",
		],
		Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
		Patuakhali: [
			"Patuakhali Sadar",
			"Bauphal",
			"Mirzaganj",
			"Dumki",
			"Galachipa",
			"Dashmina",
			"Rangabali",
			"Kalapara",
		],
		Pirojpur: [
			"Bhandaria",
			"Kawkhali",
			"Nesarabad",
			"Pirojpur Sadar",
			"Mathbaria",
			"Nazirpur",
			"Indurkani",
		],
	},
	Chittagong: {
		District: ["Thana"],
		Brahmanbaria: [
			"Brahmanbaria Sadar",
			"Kasba",
			"Nabinagar",
			"Nasirnagar",
			"Bijoynagar",
			"Bancharampur",
			"Sarail",
			"Akhaura",
			"Ashuganj",
		],
		Chandpur: [
			"Haimchar",
			"Hajiganj",
			"Kachua",
			"Matlab Dakshin",
			"Matlab Uttar",
			"Shahrasti",
		],
		Chittagong: [
			"Anwara",
			"Banshkhali",
			"Boalkhali",
			"Chandanaish",
			"Fatikchhari",
			"Hathazari",
			"Karnaphuli",
			"Rangunia",
			"Sandwip",
			"LOHAGARA",
			"Mirsharai",
			"Patiya",
			"Raozan",
			"Satkania",
			"Sitakunda",
		],
		Comilla: [
			"Barura",
			"Brahmanpara",
			"Burichang",
			"Chandina",
			"Chauddagram",
			"Comilla Sadar",
			"Comilla Sadar Dakshin Upazilla",
			"Daudkandi",
			"Debidwar",
			"Homna",
			"Laksam",
			"Lalmai",
			"Monohorgonj",
			"Meghna",
			"Muradnagar",
			"Nangalkot",
			"Titas",
		],
		Coxsbazar: [
			"Chakaria",
			"Cox's Bazar Sadar",
			"Kutubdia",
			"Maheshkhali",
			"Ramu",
			"Teknaf",
			"Ukhia",
			"Pekua",
			"Eidgaon",
		],
		Feni: [
			"Feni Sadar",
			"Chagalnaiya",
			"Daganbhuiyan",
			"Parshuram",
			"Sonagazi",
			"Falgazi",
		],
		Khagrachhari: [
			"Dighinala",
			"Khagrachhari Sadar",
			"Lakshmichhari",
			"Mahalchhari",
			"Manikchhari",
			"Matiranga",
			"Panchhari",
			"Ramgarh",
			"Guimara",
		],
		Lakshmipur: [
			"Lakshmipur Sadar",
			"Ramganj",
			"Raipur",
			"Ramgati",
			"Kamalnagar",
		],
		Noakhali: [
			"Senbagh",
			"Begumganj",
			"Chatkhil",
			"Companiganj",
			"Noakhali Sadar",
			"Hatiya",
			"Kabirhat",
			"Sonaimuri",
			"Suborno Char",
			"Bhashan char",
		],
		Rangamati: [
			"Rangamati Sadar",
			"Kaptai",
			"Rajasthali",
			"Belaichhari",
			"Langadu",
			"Bagaichhari",
			"Barkal",
			"Juraichhari",
			"Kaukhali",
			"Naniarchar",
		],
		Bandarban: [
			" Bandarban Sadar",
			"Thanchi",
			"Lama",
			"Naikhongchhari",
			"Ali kadam",
			"Rowangchhari",
			"Ruma",
		],
	},
	Dhaka: {
		District: ["Thana"],
		Dhaka: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj ", "Savar"],
		Gazipur: [
			"Gazipur Sadar",
			"Kaliakair",
			"Kapasia",
			"Sreepur ",
			"Kaliganj",
		],
		Kishoreganj: [
			"Kuliarchar",
			"Hossainpur",
			"Pakundia",
			"Kishoreganj Sadar",
			"Bajitpur",
			"Austagram",
			"Karimganj",
			"Katiadi",
			"Tarail ",
			"Itna",
			"Nikli",
			"Mithamain",
			"Bhairab",
		],
		Madaripur: [
			"Madaripur Sadar",
			"Kalkini",
			"Dasar",
			"Rajoir",
			"Shibchar",
		],
		Manikganj: [
			"Manikganj Sadar",
			"Singair",
			"Shivalay",
			"Saturia",
			"Harirampur",
			"Ghior",
			"Daulatpur",
		],
		Munshiganj: [
			"Lohajang",
			"Sreenagar",
			"Munshiganj Sadar",
			"Sirajdikhan",
			"Tongibari",
			"Gazaria",
		],
		Narayanganj: [
			"Narayanganj Sadar",
			"Sonargaon",
			"Bandar",
			"Araihazar ",
			"Rupganj",
		],
		Narsingdi: [
			"Belabo",
			"Monohardi",
			"Narsingdi Sadar",
			"Palash ",
			"Raipura",
			"Shibpur",
		],
		Rajbari: [
			"Baliakandi",
			"Goalanda",
			"Pangsha",
			"Kalukhali",
			"Rajbari Sadar",
		],
		Shariatpur: [
			"Shariatpur Sadar",
			"Damudya",
			"Naria",
			"Zanjira",
			"Bhedarganj",
			"Gosairhat",
			"Shakhipur",
		],
		Tangail: [
			"Tangail Sadar",
			"Sakhipur",
			"Basail",
			"Madhupur",
			"Ghatail",
			"Kalihati",
			"Nagarpur",
			"Mirzapur",
			"Gopalpur",
			"Delduar",
			"Bhuapur",
			"Dhanbari",
		],
		Faridpur: [
			"Alfadanga",
			"Bhanga",
			"Boalmari",
			"Charbhadrasan",
			"Faridpur Sadar",
			"Madhukhali",
			"Nagarkanda",
			"Sadarpur",
			"Saltha",
		],
		Gopalganj: [
			"Gopalganj Sadar",
			"Kashiani",
			"Kotalipara",
			"Muksudpur",
			"Tungipara",
		],
	},
	Khulna: {
		District: ["Thana"],
		Bagerhat: [
			"Bagerhat Sadar",
			"Chitalmari",
			"Fakirhat",
			"Kachua",
			"Mollahat",
			"Mongla",
			"Morrelganj",
			"Rampal",
			"Sarankhola",
		],
		Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Jibannagar", "Damurhuda"],
		Jessore: [
			"Abhaynagar ",
			"Bagherpara",
			"Chaugachha",
			"Jhikargachha",
			"Keshabpur",
			"Jessore Sadar",
			"Manirampur",
			"Sharsha",
		],
		Jhenaidah: [
			"Jhenaidah Sadar",
			"Maheshpur",
			"Kaliganj",
			"Kotchandpur",
			"Shailkupa",
			"Harinakunda",
		],
		Khulna: [
			"Dumuria",
			"Batiaghata",
			"Dacope",
			"Phultala",
			"Dighalia",
			"Koyra",
			"Terokhada",
			"Rupsha",
			"Paikgachha",
		],
		Kushtia: [
			"Kushtia Sadar",
			"Mirpur",
			"Khoksa",
			"Bheramara",
			"Kumarkhali",
			"Daulatpur",
		],
		Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
		Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
		Narail: ["Narail Sadar", "Kalia", "Lohagara"],
		Satkhira: [
			"Satkhira Sadar",
			"Assasuni",
			"Debhata",
			"Tala",
			"Kalaroa",
			"Kaliganj",
			"Shyamnagar",
		],
	},
	Rajshahi: {
		District: ["Thana"],
		Rajshahi: [
			"Bagmara",
			"Charghat",
			"Durgapur",
			"Godagari",
			"Mohanpur",
			"Paba",
			"Bagha",
			"Puthia",
			"Tanore",
		],
		Sirajganj: [
			"Sirajganj Sadar",
			"Shahjadpur",
			"Tarash",
			"Kazipur",
			"Raiganj",
			"Belkuchi",
			"Ullahpara",
			"Kamarkhanda",
			"Chauhali",
		],
		Pabna: [
			"Atgharia",
			"Bera",
			"Bhangura",
			"Chatmohar",
			"Faridpur",
			"Ishwardi",
			"Pabna Sadar",
			"Santhia",
			"Sujanagar",
		],
		Bogura: [
			"Adamdighi",
			"Bogra Sadar",
			"Sherpur",
			"Dhunat",
			"Dhupchanchia",
			"Gabtali",
			"Kahaloo",
			"Nandigram",
			"Shajahanpur",
			"Sariakandi",
			"Shibganj",
			"Sonatala",
		],
		Chapainawabganj: [
			"Chapai Nawabganj Sadar",
			"Nachole",
			"Shibganj",
			"Gomastapur",
			"Bholahat",
		],
		Naogaon: [
			"Naogaon Sadar",
			"Atrai",
			"Dhamoirhat",
			"Badalgachhi",
			"Niamatpur",
			"Manda",
			"Mohadevpur",
			"Patnitala",
			"Porsha",
			"Sapahar",
			"Raninagar",
		],
		Joypurhat: [
			"Joypurhat Sadar",
			"Akkelpur",
			"Khetlal",
			"Panchbibi",
			"Kalai",
		],
		Natore: [
			"Natore Sadar",
			"Bagatipara",
			"Singra",
			"Boraigram",
			"Gurudaspur",
			"Lalpur",
		],
	},
	Sylhet: {
		District: ["Thana"],
		Habiganj: [
			"Ajmiriganj",
			"Baniachang",
			"Bahubal",
			"Chunarughat",
			"Habiganj Sadar",
			"Lakhai",
			"Madhabpur",
			"Nabiganj",
			"Shaistaganj",
		],
		Moulvibazar: [
			"Moulvibazar Sadar",
			"Kamalganj",
			"Kulaura",
			"Rajnagar",
			"reemangal",
			"Barlekha",
			"Juri",
		],
		Sunamganj: [
			"Bishwamvarpur",
			"Chhatak",
			"Shantiganj",
			"Derai",
			"Dharamapasha",
			"Dowarabazar",
			"Jagannathpur",
			"Jamalganj",
			"Sullah",
			"Sunamganj Sadar",
			"Tahirpur",
			"Moddonagar",
		],
		Sylhet: [
			"Balaganj",
			"Beanibazar",
			"Bishwanath",
			"Companiganj",
			"Dakshin Surma",
			"Fenchuganj",
			"Golapganj",
			"Gowainghat",
			"Jaintiapur",
			"Kanaighat",
			"Osmani Nagar",
			"Sylhet Sadar",
			"Zakiganj",
		],
	},
	Rangpur: {
		District: ["Thana"],
		Dinajpur: [
			"Biral",
			"Birampur",
			"Birganj",
			"Bochaganj",
			"Chirirbandar",
			"Dinajpur Sadar",
			"Ghoraghat ",
			"Hakimpur",
			"Kaharole",
			"Khansama",
			"Nawabganj",
			"Parbatipur",
			"Fulbari",
		],
		Gaibandha: [
			"Fulchhari",
			"Gaibandha Sadar",
			"Gobindaganj",
			"Palashbari",
			"Sadullapur",
			"Sundarganj",
			"Saghata",
		],
		Kurigram: [
			"Bhurungamari",
			"Char Rajibpur",
			"Chilmari",
			"Kurigram Sadar",
			"Nageshwari",
			"Phulbari",
			"Rajarhat",
			"Raomari",
			"Ulipur",
		],
		Lalmonirhat: [
			"Lalmonirhat Sadar",
			"Aditmari",
			"Kaliganj",
			"Hatibandha",
			"Patgram",
		],
		Nilphamari: [
			"Nilphamari Sadar",
			"Saidpur",
			"Jaldhaka",
			"Kishoreganj",
			"Domar",
			"Dimla",
		],
		Panchagarh: [
			"Panchagarh Sadar",
			"Debiganj",
			"Boda",
			"Atwari",
			"Tetulia",
		],
		Rangpur: [
			"Badarganj",
			"Mithapukur",
			"Gangachara",
			"Kaunia",
			"Rangpur Sadar",
			"Pirgacha",
			"Pirganj",
			"Taraganj",
		],
		Thakurgaon: [
			"Thakurgaon Sadar",
			"Baliadangi",
			"Haripur",
			"Ranisankail",
			"Pirganj",
		],
	},
	Mymensingh: {
		District: ["Thana"],
		Mymensingh: [
			"Bhaluka",
			"Trishal",
			"Haluaghat",
			"Muktagacha",
			"Dhobaura",
			"Fulbaria",
			"Gaffargaon",
			"Gauripur",
			"Ishwarganj",
			"Mymensingh Sadar",
			"Nandail",
			"Phulpur",
			"Tarakhanda",
		],
		Netrokona: [
			"Atpara",
			"Barhatta",
			"Durgapur",
			"Khaliajuri",
			"Kalmakanda",
			"Kendua",
			"Madan",
			"Mohanganj",
			"Netrokona Sadar",
			"Purbadhala",
		],
		Jamalpur: ["Dewanganj", "Baksiganj", "Islampur", "Jamalpur Sadar"],
		Sherpur: [
			"Sherpur Sadar",
			"Nalitabari",
			"Sreebardi",
			"Jhenaigati",
			"Nakla",
		],
	},
};

export const qualifications = ["PSC", "JSC", "SSC", "HSC", "BSc", "MSc", "PhD"];
